---
# Tasks for postgresql

- name: install repo for postgrelsql10
  yum:
    name: https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7-x86_64/pgdg-centos10-10-2.noarch.rpm
    state: present

- name: install postgresql10
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - postgresql10
    - postgresql10-contrib
    - postgresql10-server

- stat: path=/var/lib/pgsql/10/data
  register: postgresql_data_dir

- name: initialize database
  command: /usr/pgsql-10/bin/postgresql-10-setup initdb
  when: postgresql_data_dir.stat.exists == False

- name: start postgresql
  service:
    name: "{{ postgresql_service_name }}"
    state: started
