---

- name: install redis
  yum:
    name: redis
    state: present
  tags: redis

- name: configure redis
  template:
    src: redis.conf.j2
    dest: /etc/redis.conf
  tags: redis
  notify:
    - restart redis

- name: configure redis sentinel
  template:
    src: redis-sentinel.conf.j2
    dest: /etc/redis-sentinel.conf
  tags: redis
  notify:
    - restart redis