---
# tasks for nginx role.

- name: install nginx
  yum:
    name: nginx
    state: present

- name: open port for web server
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
    immediate: yes
  with_items:
    - http
    - https
