---
# Tasks for dotnet-core role.

- name: Install repo for dotnet core 
  yum:
    name: https://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm
    state: present

- name: Install libicu 
  yum:
    name: "libicu"
    state: present

- name: Install libunwind
  yum:
    name: "libunwind"
    state: present

- name: Install dotnet runtime
  yum:
    name: "{{ dotnet_runtime_version }}"
    state: present
