---
# Tasks for dotnet-core role.

- name: install repo for dotnet core 
  yum:
    name: https://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm
    state: present

- name: install dotnet core dependencies 
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - libicu
    - libunwind

- name: install dotnet runtime
  yum:
    name: "{{ dotnet_runtime_version }}"
    state: present
