---
# This role contains common plays that will run all nodes.

- name: Install epel
  yum:
    name: epel-release
    state: present

- name: Install ntp
  yum:
    name: ntp
    state: present
  tags: ntp

- name: Configure ntp file
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  tags: ntp
  notify:
    - restart ntp

- name: Start the ntp service
  service:
    name: ntpd 
    state: started
    enabled: yes
  tags: ntp
