---

- name: reload postgresql
  service:
    name: "{{ postgresql_service_name }}"
    state: reloaded

- name: restart postgresql
  service:
    name: "{{ postgresql_service_name }}"
    state: restarted
